module.exports = {
  outputDir: 'docs',
  productionSourceMap: false,
  publicPath: process.env.NODE_ENV === 'production' ? '../' : '/',
  pwa: {
    workboxPluginMode: 'InjectManifest',
    workboxOptions: {
      swSrc: 'src/service-worker.js',
      exclude: [/\.jpg$/, /\.png$/],
    },
  },
  pages: {
    commercial_bank: {
      entry: 'src/main.js',
      template: 'public/commercial_bank/index.html',
      filename: 'commercial_bank/index.html',
      title: 'U+ Commercial Bank',
      chunks: ['chunk-vendors', 'chunk-common', 'commercial_bank'],
    },
    commercial_bankaccount: {
      entry: 'src/main.js',
      template: 'public/commercial_bank/index.html',
      filename: 'commercial_bank/account.html',
      title: 'U+ Commercial Bank',
      chunks: ['chunk-vendors', 'chunk-common', 'commercial_bank'],
    },
    commercial_banksettings: {
      entry: 'src/main.js',
      template: 'public/commercial_bank/index.html',
      filename: 'commercial_bank/settings.html',
      title: 'U+ Commercial Bank',
      chunks: ['chunk-vendors', 'chunk-common', 'commercial_bank'],
    },
    commercial_bankoffer: {
      entry: 'src/main.js',
      template: 'public/commercial_bank/index.html',
      filename: 'commercial_bank/offer.html',
      title: 'U+ Commercial Bank',
      chunks: ['chunk-vendors', 'chunk-common', 'commercial_bank'],
    },
    commercial_banklanding: {
      entry: 'src/main.js',
      template: 'public/commercial_bank/index.html',
      filename: 'commercial_bank/landingpage.html',
      title: 'U+ Commercial Bank',
      chunks: ['chunk-vendors', 'chunk-common', 'commercial_bank'],
    },
    retail_bank: {
      entry: 'src/main.js',
      template: 'public/retail_bank/index.html',
      filename: 'retail_bank/index.html',
      title: 'U+ Retail Bank',
      chunks: ['chunk-vendors', 'chunk-common', 'retail_bank'],
    },
    retail_bankaccount: {
      entry: 'src/main.js',
      template: 'public/retail_bank/index.html',
      filename: 'retail_bank/account.html',
      title: 'U+ Retail Bank',
      chunks: ['chunk-vendors', 'chunk-common', 'retail_bank'],
    },
    retail_banksettings: {
      entry: 'src/main.js',
      template: 'public/retail_bank/index.html',
      filename: 'retail_bank/settings.html',
      title: 'U+ Retail Bank',
      chunks: ['chunk-vendors', 'chunk-common', 'retail_bank'],
    },
    retail_bankoffer: {
      entry: 'src/main.js',
      template: 'public/retail_bank/index.html',
      filename: 'retail_bank/offer.html',
      title: 'U+ Retail Bank',
      chunks: ['chunk-vendors', 'chunk-common', 'retail_bank'],
    },
    retail_banklanding: {
      entry: 'src/main.js',
      template: 'public/retail_bank/index.html',
      filename: 'retail_bank/landingpage.html',
      title: 'U+ Retail Bank',
      chunks: ['chunk-vendors', 'chunk-common', 'retail_bank'],
    },
    retail_bankcategory: {
      entry: 'src/main.js',
      template: 'public/retail_bank/index.html',
      filename: 'retail_bank/category.html',
      title: 'U+ Retail Bank',
      chunks: ['chunk-vendors', 'chunk-common', 'retail_bank'],
    },
    comms: {
      entry: 'src/main.js',
      template: 'public/comms/index.html',
      filename: 'comms/index.html',
      title: 'U+ Comms',
      chunks: ['chunk-vendors', 'chunk-common', 'comms'],
    },
    commsaccount: {
      entry: 'src/main.js',
      template: 'public/comms/index.html',
      filename: 'comms/account.html',
      title: 'U+ Comms',
      chunks: ['chunk-vendors', 'chunk-common', 'comms'],
    },
    commssettings: {
      entry: 'src/main.js',
      template: 'public/comms/index.html',
      filename: 'comms/settings.html',
      title: 'U+ Comms',
      chunks: ['chunk-vendors', 'chunk-common', 'comms'],
    },
    commsoffer: {
      entry: 'src/main.js',
      template: 'public/comms/index.html',
      filename: 'comms/offer.html',
      title: 'U+ Comms',
      chunks: ['chunk-vendors', 'chunk-common', 'comms'],
    },
    commslanding: {
      entry: 'src/main.js',
      template: 'public/comms/index.html',
      filename: 'comms/landingpage.html',
      title: 'U+ Comms',
      chunks: ['chunk-vendors', 'chunk-common', 'comms'],
    },
    health_payer: {
      entry: 'src/main.js',
      template: 'public/health_payer/index.html',
      filename: 'health_payer/index.html',
      title: 'U+ Health',
      chunks: ['chunk-vendors', 'chunk-common', 'health_payer'],
    },
    health_payer_account: {
      entry: 'src/main.js',
      template: 'public/health_payer/index.html',
      filename: 'health_payer/account.html',
      title: 'U+ Health',
      chunks: ['chunk-vendors', 'chunk-common', 'health_payer'],
    },
    health_payer_settings: {
      entry: 'src/main.js',
      template: 'public/health_payer/index.html',
      filename: 'health_payer/settings.html',
      title: 'U+ Health',
      chunks: ['chunk-vendors', 'chunk-common', 'health_payer'],
    },
    health_payer_offer: {
      entry: 'src/main.js',
      template: 'public/health_payer/index.html',
      filename: 'health_payer/offer.html',
      title: 'U+ Health',
      chunks: ['chunk-vendors', 'chunk-common', 'health_payer'],
    },
    health_payer_landing: {
      entry: 'src/main.js',
      template: 'public/health_payer/index.html',
      filename: 'health_payer/landingpage.html',
      title: 'U+ Health',
      chunks: ['chunk-vendors', 'chunk-common', 'health_payer'],
    },
    health_provider: {
      entry: 'src/main.js',
      template: 'public/health_provider/index.html',
      filename: 'health_provider/index.html',
      title: 'U+ Health',
      chunks: ['chunk-vendors', 'chunk-common', 'health_provider'],
    },
    health_provider_account: {
      entry: 'src/main.js',
      template: 'public/health_provider/index.html',
      filename: 'health_provider/account.html',
      title: 'U+ Health',
      chunks: ['chunk-vendors', 'chunk-common', 'health_provider'],
    },
    health_provider_settings: {
      entry: 'src/main.js',
      template: 'public/health_provider/index.html',
      filename: 'health_provider/settings.html',
      title: 'U+ Health',
      chunks: ['chunk-vendors', 'chunk-common', 'health_provider'],
    },
    health_provider_offer: {
      entry: 'src/main.js',
      template: 'public/health_provider/index.html',
      filename: 'health_provider/offer.html',
      title: 'U+ Health',
      chunks: ['chunk-vendors', 'chunk-common', 'health_provider'],
    },
    health_provider_landing: {
      entry: 'src/main.js',
      template: 'public/health_provider/index.html',
      filename: 'health_provider/landingpage.html',
      title: 'U+ Health',
      chunks: ['chunk-vendors', 'chunk-common', 'health_provider'],
    },
    gov: {
      entry: 'src/main.js',
      template: 'public/gov/index.html',
      filename: 'gov/index.html',
      title: 'U+ Gov',
      chunks: ['chunk-vendors', 'chunk-common', 'gov'],
    },
    govaccount: {
      entry: 'src/main.js',
      template: 'public/gov/index.html',
      filename: 'gov/account.html',
      title: 'U+ Gov',
      chunks: ['chunk-vendors', 'chunk-common', 'gov'],
    },
    govsettings: {
      entry: 'src/main.js',
      template: 'public/gov/index.html',
      filename: 'gov/settings.html',
      title: 'U+ Gov',
      chunks: ['chunk-vendors', 'chunk-common', 'gov'],
    },
    govoffer: {
      entry: 'src/main.js',
      template: 'public/gov/index.html',
      filename: 'gov/offer.html',
      title: 'U+ Gov',
      chunks: ['chunk-vendors', 'chunk-common', 'gov'],
    },
    govlanding: {
      entry: 'src/main.js',
      template: 'public/gov/index.html',
      filename: 'gov/landingpage.html',
      title: 'U+ Gov',
      chunks: ['chunk-vendors', 'chunk-common', 'gov'],
    },
    insurance: {
      entry: 'src/main.js',
      template: 'public/insurance/index.html',
      filename: 'insurance/index.html',
      title: 'U+ Insurance',
      chunks: ['chunk-vendors', 'chunk-common', 'insurance'],
    },
    insuranceaccount: {
      entry: 'src/main.js',
      template: 'public/insurance/index.html',
      filename: 'insurance/account.html',
      title: 'U+ Insurance',
      chunks: ['chunk-vendors', 'chunk-common', 'insurance'],
    },
    insurancesettings: {
      entry: 'src/main.js',
      template: 'public/insurance/index.html',
      filename: 'insurance/settings.html',
      title: 'U+ Insurance',
      chunks: ['chunk-vendors', 'chunk-common', 'insurance'],
    },
    insuranceoffer: {
      entry: 'src/main.js',
      template: 'public/insurance/index.html',
      filename: 'insurance/offer.html',
      title: 'U+ Insurance',
      chunks: ['chunk-vendors', 'chunk-common', 'insurance'],
    },
    insurancelanding: {
      entry: 'src/main.js',
      template: 'public/insurance/index.html',
      filename: 'insurance/landingpage.html',
      title: 'U+ Insurance',
      chunks: ['chunk-vendors', 'chunk-common', 'insurance'],
    },
    manufacturing: {
      entry: 'src/main.js',
      template: 'public/manufacturing/index.html',
      filename: 'manufacturing/index.html',
      title: 'U+ Manufacturing',
      chunks: ['chunk-vendors', 'chunk-common', 'manufacturing'],
    },
    manufacturingaccount: {
      entry: 'src/main.js',
      template: 'public/manufacturing/index.html',
      filename: 'manufacturing/account.html',
      title: 'U+ Manufacturing',
      chunks: ['chunk-vendors', 'chunk-common', 'manufacturing'],
    },
    manufacturingsettings: {
      entry: 'src/main.js',
      template: 'public/manufacturing/index.html',
      filename: 'manufacturing/settings.html',
      title: 'U+ Manufacturing',
      chunks: ['chunk-vendors', 'chunk-common', 'manufacturing'],
    },
    manufacturingoffer: {
      entry: 'src/main.js',
      template: 'public/manufacturing/index.html',
      filename: 'manufacturing/offer.html',
      title: 'U+ Manufacturing',
      chunks: ['chunk-vendors', 'chunk-common', 'manufacturing'],
    },
    manufacturinglanding: {
      entry: 'src/main.js',
      template: 'public/manufacturing/index.html',
      filename: 'manufacturing/landingpage.html',
      title: 'U+ Manufacturing',
      chunks: ['chunk-vendors', 'chunk-common', 'manufacturing'],
    },
  },
};
